import "RDGlobal.idl";
import "RDPath.idl";
import "PDFPage.idl";
import "PDFSign.idl";
import "RDBmp.idl";
import "RDSoftBmp.idl";
namespace RDUILib
{
    [default_interface]
    runtimeclass PDFAnnot
    {
        PDFAnnot(Int64 page, Int64 hand);
        Int64 Handle{ get; };
        Boolean DoReset();
        UInt8[] Export();
        Boolean FlateFromPage();
        Boolean Get3DData(String save_path);
        String Get3DName();
        Boolean GetAttachmentData(String save_path);
        String GetAttachmentName();
        Int32 GetCheckStatus();
        String GetComboItem(Int32 item);
        String GetFieldJS(Int32 idx);
        RDPoint GetLinePoint(Int32 index);
        String GetListItem(Int32 item);
        Boolean GetMovieData(String save_path);
        String GetMovieName();
        Boolean GetRenditionData(String save_path);
        String GetRenditionName();
        PDFAnnot GetReply(Int32 idx);
        Boolean GetRichMediaData(String name, String save_path);
        String GetRichMediaItemAsset(Int32 idx);
        String GetRichMediaItemPara(Int32 idx);
        String GetRichMediaItemSource(Int32 idx);
        Boolean GetRichMediaItemSourceData(Int32 idx, String save_path);
        Int32 GetRichMediaItemType(Int32 idx);
        Int32[] GetSoundData(String save_path);
        String GetSoundName();
        Boolean IsResetButton();
        Boolean MoveToPage(PDFPage page, RDRect rect);
        Boolean RemoveFromPage();
        Boolean RenderToBmp(RDBmp bmp);
        Boolean RenderToSoftBmp(RDSoftBmp bmp);
        Boolean SetCheckValue(Boolean check);
        Boolean SetEditFont(PDFDocFont font);
        Boolean SetLinePoint(Single x1, Single y1, Single x2, Single y2);
        Boolean SetRadio();
        Int32 SignField(PDFDocForm form, String cert_file, String pswd, String name, String reason, String location, String contact);
        Int32 ComboItemCount{ get; };
        Int32 ComboItemSel{ get; set; };
        Int32 Dest{ get; };
        String EditText{ get; set; };
        Int32 EditTextAlign{ get; set; };
        UInt32 EditTextColor{ get; set; };
        RDRect EditTextRect{ get; };
        Single EditTextSize{ get; };
        Int32 EditType{ get; };
        String FieldFullName{ get; };
        String FieldFullName2{ get; };
        String FieldName{ get; };
        String FieldNameWithNO{ get; };
        Int32 FieldType{ get; };
        String FileLink{ get; };
        Int32 FillColor{ get; set; };
        Boolean Hide{ get; set; };
        Int32 Icon{ get; set; };
        Int32 IndexInPage{ get; };
        RDPath InkPath{ get; set; };
        Boolean Is3D{ get; };
        Boolean IsAttachment{ get; };
        Boolean IsFileLink{ get; };
        Boolean IsMovie{ get; };
        Boolean IsPopup{ get; };
        Boolean IsRemoteDest{ get; };
        Boolean IsSound{ get; };
        Boolean IsURI{ get; };
        String JS{ get; };
        Int32 LineStyle{ get; set; };
        Int32 ListItemCount{ get; };
        Int32[] ListItemSel{ get; set; };
        Boolean Locked{ get; set; };
        Boolean LockedContent{ get; };
        RDPath PolygonPath{ get; set; };
        RDPath PolylinePath{ get; set; };
        PDFAnnot Popup{ get; };
        String PopupLabel{ get; set; };
        Boolean PopupOpen{ get; set; };
        String PopupSubject{ get; set; };
        String PopupText{ get; set; };
        Boolean ReadOnly{ get; set; };
        RDRect Rect{ get; set; };
        String RemoteDest{ get; };
        Int32 ReplyCount{ get; };
        Int32 RichMediaItemActived{ get; };
        Int32 RichMediaItemCount{ get; };
        PDFSign Sign{ get; };
        Int32 SignStatus{ get; };
        Int32 StrokeColor{ get; set; };
        Single[] StrokeDash{ get; set; };
        Single StrokeWidth{ get; set; };
        String SubmitPara{ get; };
        String SubmitTarget{ get; };
        Int32 Type{ get; };
        String URI{ get; };
    }
}
