import "RDDIB.idl";
namespace RDUILib
{
    [default_interface]
    runtimeclass RDSoftBmp
    {
		RDSoftBmp(Int32 w, Int32 h);
        Int64 Handle{ get; };
		Boolean SaveJPG(String path, Int32 quality);
		void Reset(UInt32 color);
		void DrawDIB(RDDIB src, Int32 x, Int32 y);
		Int32 Width{ get; };
		Int32 Height{ get; };
	}
}
